var quotes = [
  'Berry College',
  'Agnes Scott College',
  'American InterContinental University',
  'Art Institute of Atlanta',
  'Atlanta Christian College',
  'Atlanta College of Art',
  'Brenau University',
  'Brewton-Parker College',
  'Clark Atlanta University',
  'Covenant College',
  'Dalton State College',
  'Emmanuel College',
  'Emory University',
  'Institute of Paper Science & Technology',
  'LaGrange College',
  'Life University',
  'Mercer University',
  'Morehouse College',
  'Morris Brown College',
  'Oglethorpe University',
  'Paine College',
  'Piedmont College',
  'Reinhardt College',
  'Savannah College of Art & Design',
  'Shorter College',
  'South University',
  'Spelman College',
  'Thomas University',
  'Toccoa Falls College',
  'Albany State University',
  'Armstrong Atlantic State University',
  'Clayton College & State University',
  'Columbus State University',
  'Fort Valley State University',
  'Georgia College & State University',
  'Georgia Institute of Technology',
  'Georgia Southern University',
  'Georgia Southwestern State University',
  'Georgia State University',
  'Kennesaw State University',
  'Macon State College',
  'Medical College of Georgia',
  'Middle Georgia College',
  'North Georgia College & State University',
  'Savannah State University',
  'Southern Polytechnic State University',
  'State University of West Georgia',
  'University of Georgia',
  'Valdosta State University',
  'Wesleyan College',
//Alabama
'Air University',
'Alabama A&M University',
'Alabama State University',
'Athens State University',
'Auburn University',
'Auburn University at Montgomery',
'Birmingham-Southern College',
'Concordia College-Selma',
'Faulkner University',
'Huntingdon College',
'Jacksonville State University',
'Judson College',
'Miles College',
'Oakwood College',
'Samford University',
'Southeastern Bible College',
'Southern Christian University',
'Spring Hill College',
'Stillman College',
'Talladega College',
'Troy State University',
'Tuskegee University',
'United States Sports Academy',
'University of Alabama',
'University of Mobile',
'University of Montevallo',
'University of North Alabama',
'University of South Alabama',
'University of West Alabama',

//Alaska
'Alaska Bible College',
'Alaska Pacific University',
'Sheldon Jackson College',
'University of Alaska',

//Arizona
'American Graduate School of International Management',
'American Indian College of the Assemblies of God',
'Arizona State University',
'Arizona State University East',
'Arizona State University West',
'DeVry University-Phoenix',
'Embry-Riddle Aeronautical University',
'Grand Canyon University',
'Northern Arizona University',
'Prescott College',
'Southwestern College',
'University of Arizona',
'University of Phoenix',
'Western International University',

//Arkansas
'Arkansas Baptist College',
'Arkansas State University, Jonesboro',
'Arkansas Tech University',
'Central Baptist College',
'Harding University',
'Henderson State University',
'Hendrix College',
'John Brown University',
'Lyon College',
'Ouachita Baptist University',
'Philander Smith College',
'Southern Arkansas University',
'University of Arkansas',
'University of Central Arkansas',
'University of the Ozarks',
'Williams Baptist College',

//California
'Alliant International University',
'Antioch University-Los Angeles',
'Art Center College of Design',
'Azusa Pacific University',
'Bethany College',
'Biola University',
'California Baptist University',
'California College of Arts & Crafts',
'California Institute of the Arts',
'California Institute of Integral Studies',
'California Institute of Technology',
'California Lutheran University',
'California National University',
'California Pacific University',
'California State University, Bakersfield',
'California Maritime Academy',
'California Polytechnic State University, San Luis Obispo',
'California State Polytechnic University, Pomona',
'California State University ,Channel Islands',
'California State University, Chico',
'California State University, Dominguez Hills',
'California State University, Fresno',
'California State University, Fullerton',
'California State University, Hayward',
'California State University, Long Beach',
'California State University, Los Angeles',
'California State University, Monterey Bay',
'California State University, Northridge',
'California State University, Sacramento',
'California State University, San Bernardino',
'California State University, San Marcos',
'California State University, Stanislaus',
'Humboldt State University',
'San Diego State University',
'San Francisco State University',
'San Jose State University',
'Sonoma State University',
'Chapman University',
'Christian Heritage College',
'Claremont McKenna College',
'Harvey Mudd College',
'Pitzer College',
'Pomona College',
'Scripps College',
'Cogswell Polytechnical College',
'Concordia University-Irvine',
'Defense Language Institute',
'DeVry University-Long Beach',
'DeVry University-Pomona',
'Dominican University of California',
'Fielding Graduate Institute',
'Fresno Pacific University',
'Fuller Theological Seminary',
'Golden Gate University',
'Holy Names College',
'Hope International University',
'Humphreys College',
'Institute of Transpersonal Psychology',
'John F. Kennedy University',
'La Sierra University',
'Life Pacific College',
'Lincoln University',
'Loma Linda University',
'Loyola Marymount University',
'Marymount College',
'The Masters College',
'The Masters Seminary',
'Menlo College',
'Mills College',
'Monterey Institute of International Studies',
'Mount St. Marys College',
'National Hispanic University',
'National University',
'Naval Postgraduate School',
'New College of California',
'Notre Dame de Namur University',
'Occidental College',
'Otis College of Art & Design',
'Pacific Oaks College',
'Pacific Union College',
'Pacifica Graduate Institute',
'Patten College',
'Pepperdine University',
'Platt College',
'Point Loma Nazarene College',
'Saint Marys College of California',
'Samuel Merritt College',
'San Jose Christian College',
'Santa Clara University',
'Saybrook Graduate School & Research Center',
'Simpson College',
'Southern California Institute of Architecture',
'Southwestern University School of Law',
'Stanford University',
'Thomas Aquinas College',
'University of California, Berkeley',
'University of California, Davis',
'University of California, Hastings College of the Law',
'University of California, Irvine',
'University of California, Los Angeles',
'University of California, Merced',
'University of California, Riverside',
'University of California, San Diego',
'University of California, San Francisco',
'University of California, Santa Barbara',
'University of California, Santa Cruz',
'University of Judaism',
'University of La Verne',
'University of Northern California',
'University of the Pacific',
'University of Redlands',
'University of San Diego',
'University of San Francisco',
'University of Southern California',
'University of West Los Angeles',
'Vanguard University of Southern California',
'Western State University College of Law',
'Western University of Health Sciences',
'Westminster Theological Seminary in California',
'Westmont College',
'Whittier College',
'William Howard Taft University',
'Woodbury University',

//Colorado
'Adams State College',
'Colorado Christian University',
'Colorado College',
'Colorado School of Mines',
'Colorado State University',
'Colorado Technical University',
'Fort Lewis College',
'Jones International University',
'Mesa State College',
'Metropolitan State College of Denver',
'Naropa Institute',
'National Technological University',
'Nazarene Bible College',
'Regis University',
'Rocky Mountain College of Art & Design',
'United States Air Force Academy',
'University of Colorado, Boulder',
'University of Colorado, Colorado Springs',
'University of Colorado, Denver',
'University of Colorado, Health Sciences Center',
'University of Denver',
'University of Northern Colorado',
'University of Southern Colorado',
'Western State College',

//Connecticut
'Albertus Magnus College',
'Central Connecticut State University',
'Charter Oak State College',
'Connecticut College',
'Eastern Connecticut State University',
'Fairfield University',
'Holy Apostles College & Seminary',
'Mitchell College',
'Quinnipiac College',
'Rensselaer at Hartford',
'Sacred Heart University',
'St. Joseph College',
'Southern Connecticut State University',
'Teikyo Post University',
'Trinity College',
'United States Coast Guard Academy',
'University of Bridgeport',
'University of Connecticut',
'University of Hartford',
'University of New Haven',
'Wesleyan University',
'Western Connecticut State University',
'Yale University',

//Delaware
'Delaware State University',
'Goldey-Beacom College',
'University of Delaware',
'Wesley College',
'Wilmington College',

//District of Columbia
'American University',
'The Catholic University of America',
'Corcoran College of Art & Design',
'Gallaudet University',
'George Washington University',
'Georgetown University',
'Howard University',
'National Defense University',
'Southeastern University',
'Strayer University',
'Trinity College',
'University of the District of Columbia',

//Florida
'The Baptist College of Florida',
'Barry University',
'Bethune-Cookman College',
'Carlos Albizu University-Miami',
'Clearwater Christian College',
'DeVry University-Orlando',
'Eckerd College',
'Edward Waters College',
'Embry-Riddle Aeronautical University',
'Flagler College',
'Florida Agricultural & Mechanical University',
'Florida Atlantic University',
'Florida Christian College',
'Florida College',
'Florida Gulf Coast University',
'Florida Hospital College of Health Sciences',
'Florida Institute of Technology',
'Florida International University',
'Florida Memorial College',
'Florida Metropolitan University',
'Florida Southern College',
'Florida State University',
'Hobe Sound Bible College',
'International College',
'International Fine Arts College',
'Jacksonville University',
'Jones College',
'Lynn University',
'Northwood University',
'Nova Southeastern University',
'Palm Beach Atlantic College',
'Ringling School of Art & Design',
'Rollins College',
'Saint John Vianney College Seminary',
'Saint Leo College',
'St. Thomas University',
'South Florida Bible College & Theological Seminary',
'Southeastern College of the Assemblies of God',
'Stetson University',
'Trinity College of Florida',
'Troy State University-Florida Region',
'University of Central Florida',
'University of Florida',
'University of Miami',
'University of North Florida',
'University of South Florida',
'University of Tampa',
'University of West Florida',
'Warner Southern College',
'Webber College',

//Hawaii
'Brigham Young University-Hawaii',
'Chaminade University',
'Hawaii Pacific University',
'University of Hawaii, Hilo',
'University of Hawaii, Manoa',
'University of Hawaii, West Oahu',

//Idaho
'Albertson College of Idaho',
'Boise State University',
'Brigham Young University-Idaho',
'Idaho State University',
'Lewis-Clark State College',
'Northwest Nazarene College',
'University of Idaho',

//Illinois
'Augustana College',
'Aurora University',
'Barat College',
'Benedictine University',
'Blackburn College',
'Bradley University',
'The Chicago School of Professional Psychology',
'Chicago State University',
'College of DuPage',
'Columbia College',
'Concordia University-River Forest',
'DePaul University',
'DeVry University',
'DeVry University-Chicago',
'DeVry University-DuPage',
'Dominican University',
'East-West University',
'Eastern Illinois University',
'Elmhurst College',
'Erikson Institute',
'Eureka College',
'Governors State University',
'Greenville College',
'Illinois College',
'Illinois Institute of Technology',
'Illinois State University',
'Illinois Wesleyan University',
'Judson College',
'Kendall College',
'Knox College',
'Lake Forest College',
'Lakeview College of Nursing',
'Lewis University',
'Lincoln Christian College & Seminary',
'Loyola University Chicago',
'Lutheran School of Theology at Chicago',
'McKendree College',
'McMurray College',
'Midwestern University',
'Millikin University',
'Monmouth College',
'Moody Bible Institute',
'National University of Health Sciences',
'National-Louis University',
'North Central College',
'North Park University',
'Northeastern Illinois University',
'Northern Illinois University',
'Northwestern University',
'Olivet Nazarene University',
'Principia College',
'Quincy University',
'Robert Morris College',
'Rockford College',
'Roosevelt University',
'Rush University',
'Saint Anthony College of Nursing',
'St. Xavier University',
'School of the Art Institute of Chicago',
'Shimer College',
'Southern Illinois University System, Carbondale',
'Southern Illinois University System, Edwardsville',
'Spertus Institute of Jewish Studies',
'Trinity Christian College',
'Trinity International University',
'University of Chicago',
'University of Illinois, Chicago',
'University of Illinois, Springfield',
'University of Illinois, Urbana-Champaign',
'University of St. Francis',
'Western Illinois University',
'Wheaton College',

//Indiana
'Anderson University',
'Ball State University',
'Bethel College',
'Butler University',
'Calumet College of St. Joseph',
'Christian Theological Seminary',
'Concordia Theological Seminary-Fort Wayne',
'DePauw University',
'Earlham College',
'Franklin College',
'Goshen College',
'Grace College',
'Hanover College',
'Holy Cross College',
'Huntington College',
'Indiana Institute of Technology',
'Indiana State University',
'Indiana University-Bloomington',
'Indiana University-East',
'Indiana University-Kokomo',
'Indiana University-Northwest',
'Indiana University-South Bend',
'Indiana University-Southeast',
'Indiana University/Purdue University at Columbus',
'Indiana University/Purdue University at Fort Wayne',
'Indiana University/Purdue University at Indianapolis',
'Indiana Wesleyan University, Marion',
'Manchester College',
'Marian College',
'Martin University',
'Oakland City University',
'Purdue University',
'Purdue University Calumet',
'Purdue University North Central',
'Indiana University/Purdue University at Columbus',
'Indiana University/Purdue University at Fort Wayne',
'Indiana University/Purdue University at Indianapolis',
'School of Technology at Anderson',
'School of Technology at Columbus',
'School of Technology at Indianapolis',
'School of Technology at Kokomo',
'School of Technology at Muncie',
'School of Technology at New Albany',
'School of Technology at Richmond',
'School of Technology at South Bend/Elkhart',
'School of Technology at Versailles',
'Rose-Hulman Institute of Technology',
'Saint Josephs College',
'Saint Mary-of-the-Woods College',
'Saint Marys College',
'Taylor University',
'Tri-State University',
'University of Evansville',
'University of Indianapolis',
'University of Notre Dame',
'University of Saint Francis',
'University of Southern Indiana',
'Valparaiso University',
'Wabash College',

//Iowa
'Allen College',
'Briar Cliff College',
'Buena Vista University',
'Central College',
'Clarke College',
'Coe College',
'Cornell College',
'Des Moines University-Osteopathic Medical Center',
'Divine Word College',
'Dordt College',
'Drake University',
'Emmaus Bible College',
'Faith Baptist Bible College & Theological Seminary',
'Graceland College',
'Grand View College',
'Grinnell College',
'Iowa State University',
'Iowa Wesleyan College',
'Loras College',
'Luther College',
'Maharishi University of Management',
'Marycrest International University',
'Morningside College',
'Mount Mercy College',
'Mount St. Clare College',
'Northwestern College of Iowa',
'St. Ambrose University',
'Simpson College',
'University of Dubuque',
'University of Iowa',
'University of Northern Iowa',
'Upper Iowa University',
'Vennard College',
'Waldorf College',
'Wartburg College',
'William Penn College',

//Kansas
'Baker University',
'Barclay College',
'Benedictine College',
'Bethany College',
'Bethel College',
'Central Christian College',
'Emporia State University',
'Fort Hays State University',
'Friends University',
'Haskell Indian Nations University',
'Hesston College',
'Kansas State University',
'Kansas Wesleyan University',
'Manhattan Christian College',
'McPherson College',
'Mid-America Nazarene College',
'Newman University',
'Ottawa University',
'Pittsburg State University',
'Saint Mary College',
'Southwestern College',
'Sterling College',
'Tabor College',
'University of Kansas',
'University of Kansas Medical Center',
'Washburn University',
'Wichita State University',

//Kentucky
'Alice Lloyd College',
'Asbury College',
'Asbury Theological Seminary',
'Bellarmine College',
'Berea College',
'Brescia University',
'Campbellsville University',
'Centre College',
'Clear Creek Baptist Bible College',
'Cumberland College',
'Eastern Kentucky University',
'Georgetown College',
'Kentucky Christian College',
'Kentucky Mountain Bible College',
'Kentucky State University',
'Kentucky Wesleyan College',
'Lindsey Wilson College',
'Mid-Continent College',
'Midway College',
'Morehead State University',
'Murray State University',
'Northern Kentucky University',
'Pikeville College',
'Southern Baptist Theological Seminary',
'Spalding University',
'Sullivan University',
'Thomas More College',
'Transylvania University',
'Union College',
'University of Kentucky',
'University of Louisville',
'Western Kentucky University',

//Louisiana
'Centenary College of Louisiana',
'Dillard University',
'Grambling State University',
'Louisiana College',
'Louisiana State University',
'Louisiana State University Alexandria, Louisiana',
'Louisiana State University Baton Rouge, Louisiana',
'Louisiana State University Eunice, Louisiana',
'Louisiana State University Health Sciences Center',
'Louisiana State University Shreveport, Louisiana',
'University of New Orleans',
'Louisiana Tech University',
'Loyola University New Orleans',
'McNeese State University',
'Nicholls State University',
'Northwestern State University of Louisiana',
'Our Lady of Holy Cross College',
'Our Lady of the Lake College',
'Southeastern Louisiana University',
'Southern University System Baton Rouge, Louisiana',
'Southern University System New Orleans, Louisiana',
'Tulane University',
'University of Louisiana System',
'University of Louisiana System Monroe, Louisiana',
'University of Louisiana System Lafayette, Louisiana',
'Xavier University of Louisiana',

//Maine
'Bates College',
'Bowdoin College',
'Colby College',
'College of the Atlantic',
'Husson College',
'Maine College of Art',
'Maine Maritime Academy',
'St. Josephs College',
'Thomas College',
'Unity College',
'University of Maine Augusta, Maine',
'University of Maine Farmington Maine',
'University of Maine Fort Kent Maine',
'University of Maine Machias Maine',
'University of Maine Orono Maine',
'University of Maine Presque Isle Maine',
'University of Southern Maine',
'University of New England',

//Maryland
'Baltimore Hebrew University',
'Baltimore International College',
'Bowie State University',
'Capitol College',
'Chesapeake College',
'College of Notre Dame of Maryland',
'Columbia Union College',
'Coppin State College',
'Goucher College',
'Frostburg State University',
'Hood College',
'Johns Hopkins University',
'Loyola College',
'Maryland institute, College of Art',
'McDaniel College',
'Morgan State University',
'Mount Saint Marys College',
'St. Johns College-Annapolis',
'St. Marys College of Maryland',
'Salisbury State University',
'Soujourner-Douglass College',
'Towson University',
'The Uniformed Services University of the Health Sciences',
'United States Naval Academy',
'University of Baltimore',
'University of Maryland Baltimore, Maryland',
'University of Maryland Baltimore County, Maryland',
'University of Maryland College Park, Maryland',
'University of Maryland Eastern Shore, Maryland',
'University of Maryland University College, Maryland',
'Washington Bible College',
'Washington College',
'Villa Julie College',


//Massachusetts
'American International College',
'Amherst College',
'Anna Maria College',
'Assumption College',
'Atlantic Union College',
'Babson College',
'Bay Path College',
'Becker College',
'Benjamin Franklin Institute of Technology',
'Bentley College',
'Berklee College of Music',
'Boston College',
'Boston Conservatory',
'Boston Graduate School of Psychoanalysis',
'Boston University',
'Brandeis University',
'Bridgewater State College',
'Cambridge College',
'Clark University',
'College of the Holy Cross',
'Concord School of Management',
'Curry College',
'Eastern Nazarene College',
'Elms College',
'Emerson College',
'Emmanuel College',
'Endicott College',
'Fitchburg State College',
'Framingham State College',
'Gordon College',
'Gordon-Conwell Theological Seminary',
'Hampshire College',
'Harvard University',
'Lasell College',
'Lesley College',
'Massachusetts College of Art',
'Massachusetts College of Liberal Arts',
'Massachuetts College of Pharmacy & Health Sciences',
'Massachusetts Institute of Technology',
'Massachusetts Maritime Academy',
'Massachusetts School of Professional Psychology',
'Merrimack College',
'Mount Holyoke College',
'Mount Ida College',
'New England College of Optometry',
'New England Conservatory of Music',
'Newbury College',
'Nichols College',
'North Adams State College',
'Northeastern University',
'Pine Manor College',
'Regis College',
'Salem State College',
'Simmons College',
'Simons Rock College',
'Smith College',
'Springfield College',
'Stonehill College',
'Suffolk University',
'Tufts University',
'University of Amherst, Massachusetts',
'University of Boston, Massachusetts',
'University of Dartmouth, Massachusetts',
'University of Lowell, Massachusetts',
'Medical School at Worcester',
'Wellesley College',
'Wentworth Institute of Technology',
'Western New England College',
'Westfield State College',
'Weston Jesuit School of Theology',
'Wheaton College',
'Wheelock College',
'Williams College',
'Worcester Polytechnic Institute',
'Worcester State College',

//Michigan
'Adrian College',
'Albion College',
'Alma College',
'Andrews University',
'Aquinas College',
'Baker College',
'Calvin College',
'Central Michigan University',
'Cleary College',
'College for Creative Studies',
'Concordia College-Ann Arbor',
'Cornerstone University',
'Davenport University',
'Eastern Michigan University',
'Ferris State University',
'Finlandia University',
'Grace Bible College',
'Grand Valley State University',
'Hillsdale College',
'Hope College',
'Kalamazoo College',
'Kendall College of Art & Design',
'Kettering University',
'Lake Superior State University',
'Lawrence Technological University',
'Madonna University',
'Marygrove College',
'Michigan State University',
'Michigan Technological University',
'Northern Michigan University',
'Northwood University',
'Oakland University',
'Olivet College',
'Reformed Bible College',
'Rochester College',
'Saginaw Valley State University',
'Saint Marys College',
'Siena Heights University',
'Spring Arbor University',
'University of Detroit Mercy',
'University of Ann Arbor, Michigan',
'University of Dearborn, Michigan',
'University of Flint, Michigan',
'Walsh College',
'Wayne State University',
'Western Michigan University',
'William Tyndale College',

//Minnesota
'Alfred Adler Institute',
'Augsburg College',
'Bethany Lutheran College',
'Bethel College and Seminary',
'Capella University',
'Carleton College',
'College of Saint Benedict',
'College of St. Catherine',
'College of St. Scholastica',
'College of Visual Arts',
'Concordia College-Moorhead',
'Concordia College-St. Paul',
'Crossroads College',
'Crown College',
'Gustavus Adolphus College',
'Hamline University',
'Luther Seminary',
'Macalester College',
'Martin Luther College',
'Minneapolis College of Art & Design',
'Minnesota State University System',
'Bemidji State University',
'Minnesota State University-Mankato',
'Minnesota State University-Moorhead',
'Metropolitan State University',
'Southwest State University',
'St. Cloud State University',
'Winona State University',
'North Central University',
'Northwest College, Wyoming',
'Oak Hills Christian College',
'Pillsbury Baptist Bible College',
'Saint Johns University',
'Saint Marys University of Minnesota',
'Saint Olaf College',
'University of Crookston, Minnesota',
'University of Duluth, Minnesota',
'University of Morris, Minnesota',
'University of Twin Cities, Minnesota',
'University of Saint Thomas',
'Walden University',
'William Mitchell College of Law',

//Mississippi
'Alcorn State University',
'Belhaven College',
'Blue Mountain College',
'Delta State University',
'Jackson State University',
'Magnolia Bible College',
'Millsaps College',
'Mississippi College',
'Mississippi State University',
'Mississippi University for Women',
'Mississippi Valley State University',
'Rust College',
'Tougaloo College',
'University of Mississippi',
'University of Mississippi Medical Center',
'University of Southern Mississippi',
'William Carey College',

//Missouri
'Avila College',
'Baptist Bible College',
'Central Bible College',
'Central Christian College of the Bible',
'Central Methodist College',
'Central Missouri State University',
'Cleveland Chiropractic College',
'College of the Ozarks',
'Columbia College',
'Concordia Seminary-St. Louis',
'Culver-Stockton College',
'DeVry University-Kansas City',
'Drury University',
'Evangel University',
'Fontbonne College',
'Forest Institute of Professional Psychology',
'Greenleaf University',
'Hannibal-Lagrange College',
'Harris-Stowe State College',
'Kirksville College of Osteopathic Medicine',
'Lincoln University',
'Lindenwood University',
'Logan College of Chiropractic',
'Maryville University of St. Louis',
'Missouri Baptist College',
'Missouri Southern State College',
'Missouri Valley College',
'Missouri Western State College',
'Northwest Missouri State University',
'Ozark Christian College',
'Park University',
'Rockhurst University',
'St. Louis College of Pharmacy',
'Saint Louis University',
'Southeast Missouri State University',
'Southwest Baptist University',
'Southwest Missouri State University',
'Stephens College',
'Truman State University',
'University of Columbia, Missouri',
'University of Kansas City, Missouri',
'University of Rolla, Missouri',
'University of St. Louis, Missouri',
'Washington University, St. Louis',
'Webster University',
'Westminster College',
'William Jewell College',
'William Woods University',


//Montana

'Carroll College',
'Montana State University Billings',
'Montana State University Bozeman',
'Montana State University Northern',
'Rocky Mountain College',
'Salish Kootenai College',
'University of Great Falls',
'University of Missoula, Montana',
'University of Montana Tech, Montana',
'Western Montana College of The University of Montana',

//Nebraska
'Bellevue University',
'Chadron State College',
'Clarkson College',
'College of Saint Mary',
'Concordia University-Nebraska',
'Creighton University',
'Dana College',
'Doane College',
'Grace University',
'Hastings College',
'Midland Lutheran College',
'Nebraska Christian College',
'Nebraska Methodist College',
'Nebraska Wesleyan University',
'Peru State College',
'Union College',
'University of Kearney, Nebraska',
'University of Lincoln, Nebraska',
'University of Nebraska Medical Center',
'University of Omaha, Nebraska',
'Wayne State College',
'York College',


//Nevada
'Sierra Nevada College',
'University of Reno, Nevada',
'University of Las Vegas, Nevada',
,
,
//New Hampshire,
'Antioch New England',
'Colby-Sawyer College',
'College for Lifelong Learning',
'Daniel Webster College',
'Dartmouth College',
'Franklin Pierce College',
'Franklin Pierce Law Center',
'Keene State College',
'New England College',
'New Hampshire College',
'Notre Dame College',
'Plymouth State College',
'Rivier College',
'Saint Anselm College',
'Southern New Hampshire University',
'The Thomas More College of Liberal Arts',
'University of New Hampshire',
'University of New Hampshire at Manchester',
'White Pines College',

//New Jersey
'Berkeley College',
'Bloomfield College',
'Caldwell College',
'Centenary College',
'The College of New Jersey',
'College of Saint Elizabeth',
'Drew University',
'Fairleigh Dickinson University',
'Felician College',
'Georgian Court College',
'Kean University',
'Monmouth University',
'Montclair State University',
'New Jersey City University',
'New Jersey Institute of Technology',
'Princeton University',
'Ramapo College',
'Richard Stockton College of New Jersey',
'Rider University',
'Rowan University',
'Rutgers University, New Brunswick',
'Rutgers University, Camden',
'Rutgers University, Newark',
'Saint Peters College',
'Seton Hall University',
'Stevens Institute of Technology',
'Thomas Edison State College',
'University of Medicine & Dentistry of New Jersey',
'William Paterson University',

//New York
'Adelphi University',
'Albany College of Pharmacy',
'Albany Medical College',
'Alfred University',
'Bank Street College of Education',
'Bard College',
'Barnard College',
'Boricua College',
'Canisius College',
'Cazenovia College',
'City University of New York System, Baruch College',
'City University of New York System, Brooklyn College',
'City University of New York System, City College',
'City University of New York System, College of Staten Island',
'City University of New York System, Graduate School & University Center',
'City University of New York System, Hunter College',
'City University of New York System, John Jay College of Criminal Justice',
'City University of New York System, Lehman College',
'City University of New York System, Medger Evers College',
'City University of New York System, New York City College of Technology',
'City University of New York System, Queens College',
'City University of New York System, York College',
'Clarkson University',
'Colgate University',
'College of Aeronautics',
'College of Mount St. Vincent',
'College of New Rochelle',
'College of Saint Rose',
'Columbia University',
'Concordia College-Bronxville',
'The Cooper Union for the Advancement of Science & Art',
'Cornell University',
'Daemen College',
'Dominican College',
'Dowling College',
'DYouville College',
'Elmira College',
'Excelsior College',
'Five Towns College',
'Fordham University',
'Hamilton College',
'Hartwick College',
'Hebrew Union College-Jewish Institute of Religion',
'Hilbert College',
'Hobart and William Smith Colleges',
'Hofstra University',
'Houghton College',
'Iona College',
'Ithaca College',
'The Jewish Theological Seminary of America',
'The Juilliard School',
'Keuka College',
'Le Moyne College',
'Laboratory Institute of Merchandising',
'Long Island University, Arnold & Marie Schwartz College of Pharmacy & Health Sciences',
'Long Island University, Brentwood Campus',
'Long Island University, Brooklyn Campus',
'Long Island University, C.W. Post Campus',
'Long Island University, Rockland Graduate Campus',
'Long Island University, Southampton College',
'Long Island University, Westchester Campus',
'Manhattan College',
'Manhattan School of Music',
'Manhattanville College',
'Marist College',
'Marymount College',
'Marymount Manhattan College',
'Medaille College',
'Mercy College',
'Metropolitan College of New York',
'Molloy College',
'Monroe College',
'Mount Saint Mary College',
'Nazareth College',
'New School University',
'New York College of Podiatric Medicine',
'New York Institute of Technology',
'New York Medical College',
'New York University',
'Niagara University',
'Nyack College',
'Pace University',
'Parsons School of Design',
'Paul Smiths College',
'Polytechnic University of New York',
'Pratt Institute',
'Rensselaer Polytechnic Institute',
'Roberts Wesleyan College',
'Rochester Institute of Technology',
'The Rockefeller University',
'The Sage Colleges',
'St. Bonaventure University',
'Saint Francis College',
'St. John Fisher College',
'St. Johns University',
'St. Josephs College',
'St. Lawrence University',
'St. Thomas Aquinas College',
'Sarah Lawrence College',
'School of Visual Arts',
'Siena College',
'Skidmore College',
'State University of New York System, Albany',
'State University of New York System, Binghamton',
'State University of New York System, Buffalo',
'State University of New York System, Stony Brook',
'State University of New York System, College at Brockport',
'State University of New York System, College at Buffalo',
'State University of New York System, College at Cortland',
'State University of New York System, College at Fredonia',
'State University of New York System, College at Geneseo',
'State University of New York System, College at New Paltz',
'State University of New York System, College at Old Westbury',
'State University of New York System, College at Oneonta',
'State University of New York System, College at Oswego',
'State University of New York System, College at Plattsburgh',
'State University of New York System, College at Potsdam',
'State University of New York System, College at Purchase',
'State University of New York System, College of Agriculture & Technology at Cobleskill',
'State University of New York System, College of Agriculture & Technology at Morrisville',
'State University of New York System, College of Environmental Science & Forestry',
'State University of New York System, College of Technology at Alfred',
'State University of New York System, College of Technology at Farmingdale',
'State University of New York System, Empire State College',
'State University of New York System, Fashion Institute of Technology',
'State University of New York System, Health Science Center at Brooklyn',
'State University of New York System, Health Science Center at Syracuse',
'State University of New York System, Institute of Technology at Utica/Rome',
'State University of New York System, Maritime College at Ft. Schuyler',
'Syracuse University',
'Teachers College, Columbia University',
'Touro University International',
'Unification Theological Seminary',
'Union College',
'Union Theological Seminary',
'United States Merchant Marine Academy',
'United States Military Academy',
'University of Rochester',
'Utica College of Syracuse University',
'Vassar College',
'Wagner College',
'Webb Institute',
'Wells College',
'Yeshiva University',

//North Carolina
'Appalachian State University',
'Barber-Scotia College',
'Barton College',
'Belmont Abbey College',
'Bennett College',
'Brevard College',
'Campbell University',
'Catawba College',
'Chowan College',
'Davidson College',
'Duke University',
'East Carolina University',
'Elizabeth City State University',
'Elon University',
'Fayetteville State University',
'Gardner-Webb University',
'Greensboro College',
'Guilford College',
'High Point University',
'Johnson C. Smith University',
'Lees-McRae College',
'Lenoir-Rhyne College',
'Livingstone College',
'Louisburg College',
'Mars Hill College',
'Meredith College',
'Methodist College',
'Montreat College',
'Mount Olive College',
'North Carolina Central University',
'North Carolina A&T State University',
'North Carolina School of the Arts',
'North Carolina State University',
'North Carolina Wesleyan College',
'Peace College',
'Pfeiffer University',
'Piedmont Baptist College',
'Queens University of Charlotte',
'Roanoke Bible College',
'St. Andrews Presbyterian College',
'St. Augustines College',
'Salem College',
'Shaw University',
'University of North Carolina, Asheville',
'University of North Carolina, Chapel Hill',
'University of North Carolina, Charlotte',
'University of North Carolina, Greensboro',
'University of North Carolina, Pembroke',
'University of North Carolina, Wilmington',
'Wake Forest University',
'Warren Wilson College',
'Western Carolina University',
'Wingate University',
'Winston-Salem State University',

//North Dakota
'Dickinson State University',
'Jamestown College',
'Mayville State University',
'Minot State University',
'North Dakota State University',
'Trinity Bible College',
'University of Mary',
'University of North Dakota',
'Valley City State University',

//Ohio,
'Air Force Institute of Technology',
'Antioch College',
'Art Academy of Cincinnati',
'Ashland University',
'Baldwin-Wallace College',
'Bowling Green State University',
'Bluffton College',
'Capital University',
'Case Western Reserve University',
'Cedarville University',
'Central State University',
'Cincinnati Bible College & Seminary',
'Circleville Bible College',
'Cleveland Institute of Art',
'Cleveland Institute of Music',
'Cleveland State University',
'College of Mount St. Joseph',
'The College of Wooster',
'Columbus College of Art & Design',
'Chancellor University',
'Jack Welch Management Institute',
'Defiance College',
'Denison University',
'Franciscan University of Steubenville',
'Franklin University',
'Heidelberg College',
'Hiram College',
'John Carroll University',
'Kent State University',
'Kenyon College',
'Lake Erie College',
'Laura & Alvin Siegal College of Judaic Studies',
'Lourdes College',
'Malone College',
'Marietta College',
'Medical College of Ohio',
'Miami University of Ohio',
'Mount Union College',
'Mount Vernon Nazarene College',
'Muskingum College',
'Northeastern Ohio Universities College of Medicine',
'Notre Dame College',
'Oberlin College',
'Ohio Dominican College',
'Ohio Northern University',
'Ohio State University, Columbus',
'Ohio State University, Lima',
'Ohio State University, Mansfield',
'Ohio State University, Marion',
'Ohio Wesleyan University',
'Ohio University, Athens',
'Otterbein College',
'Shawnee State University',
'Tiffin University',
'Union Institute & University',
'University of Akron',
'University of Cincinnati',
'University of Dayton',
'The University of Findlay',
'University of Northwestern Ohio',
'University of Rio Grande',
'University of Toledo',
'Urbana University',
'Ursuline College',
'Walsh University',
'Wilberforce University',
'Wilmington College',
'Wittenberg University',
'Wright State University',
'Xavier University',
'Youngstown State University',

//Oklahoma
'Bacone College',
'Cameron University',
'East Central University',
'Langston University',
'Mid-America Bible College',
'Northeastern State University',
'Northwestern Oklahoma State University',
'Oklahoma Baptist University',
'Oklahoma Christian University of Science & Arts',
'Oklahoma City University',
'Oklahoma Panhandle State University',
'Oklahoma State University',
'Oklahoma Wesleyan University',
'Oral Roberts University',
'Phillips University (closed July 1998)',
'Rogers State University',
'St. Gregorys University',
'Southeastern Oklahoma State University',
'Southern Nazarene University',
'Southwestern Oklahoma State University',
'University of Central Oklahoma',
'University of Oklahoma',
'University of Oklahoma Health Sciences Center',
'University of Science & Arts of Oklahoma',
'University of Tulsa',

//Oregon
'Concordia University-Portland',
'Eastern Oregon University',
'Eugene Bible College',
'George Fox University',
'Gutenberg College',
'Lewis & Clark College',
'Linfield College',
'Marylhurst University',
'Mount Angel Seminary',
'Multnomah Bible College & Seminary',
'Northwest Christian College',
'Oregon Graduate Institute of Science & Technology',
'Oregon Health Sciences University',
'Oregon Institute of Technology',
'Oregon State University',
'Pacific Northwest College of Art',
'Pacific University',
'Portland State University',
'Reed College',
'Southern Oregon University',
'University of Oregon',
'University of Portland',
'Warner Pacific College',
'Western Baptist College',
'Western Oregon University',
'Western States Chiropractic College',
'Willamette University',

//Pennsylvania
'Albright College',
'Allegheny College',
'Alvernia College',
'American College',
'Arcadia University',
'Baptist Bible College',
'Bloomsburg University of Pennsylvania',
'Bryn Athyn College of the New Church',
'Bryn Mawr College',
'Bucknell University',
'Cabrini College',
'California University of Pennsylvania',
'Carlow College',
'Carnegie Mellon University',
'Cedar Crest College',
'Chatham College',
'Chestnut Hill College',
'Cheyney University',
'Clarion University of Pennsylvania',
'College Misericordia',
'Curtis Institute of Music',
'Delaware Valley College',
'DeSales University',
'Dickinson College',
'Drexel University',
'Duquesne University',
'East Stroudsburg University of Pennsylvania',
'Eastern College',
'Edinboro University of Pennsylvania',
'Elizabethtown College',
'Franklin & Marshall College',
'Gannon University',
'Geneva College',
'Gettysburg College',
'Gratz College',
'Grove City College',
'Gwynedd Mercy College',
'Haverford College in Pennsylvania',
'Holy Family College',
'Immaculata College',
'Indiana University of Pennsylvania',
'Juniata College',
'Keystone College',
'Kings College',
'Kutztown University of Pennsylvania',
'La Roche College',
'Lafayette College',
'Lancaster Bible College',
'LaSalle University',
'Lebanon Valley College',
'Lehigh University',
'Lincoln University',
'Lock Haven University of Pennsylvania',
'Lycoming College',
'Mansfield University of Pennsylvania',
'Marywood University',
'Mercyhurst College',
'Messiah College',
'Millersville University of Pennsylvania',
'Moore College of Art & Design',
'Moravian College',
'Mount Aloysius College',
'Muhlenberg College',
'Neumann College',
'Peirce College',
'Pennsylvania College of Optometry',
'Pennsylvania State University, Abington',
'Pennsylvania State University, Altoona',
'Pennsylvania State University, Beaver',
'Pennsylvania State University, Behrend College, Erie',
'Pennsylvania State University, Berks',
'Pennsylvania State University, College of Medicine',
'Pennsylvania State University, Commonwealth College',
'Pennsylvania State University, Delaware County',
'Pennsylvania State University, Dickinson School of Law',
'Pennsylvania State University, DuBois',
'Pennsylvania State University, Fayette',
'Pennsylvania State University, Great Valley',
'Pennsylvania State University, Harrisburg',
'Pennsylvania State University, Hazleton',
'Pennsylvania State University, Lehigh Valley',
'Pennsylvania State University, McKeesport',
'Pennsylvania State University, New Kensington',
'Pennsylvania State University, Mont Alto',
'Pennsylvania College of Technology',
'Pennsylvania State University, Schuylkill',
'Pennsylvania State University, Shenango',
'Pennsylvania State University',
'Pennsylvania State University, Wilkes-Barre',
'Pennsylvania State University, Worthington Scranton',
'Pennsylvania State University, York',
'Philadelphia Biblical University',
'Philadelphia College of Pharmacy & Science',
'Philadelphia University',
'Point Park Morris College',
'Robert Morris College',
'Rosemont College',
'Saint Francis College',
'Saint Josephs University',
'Saint Vincent College',
'Seton Hill College',
'Shippensburg University of Pennsylvania',
'Slippery Rock University of Pennsylvania',
'Susquehanna University',
'Swarthmore College',
'Temple University',
'Thiel College',
'Thomas Jefferson University',
'University of Pennsylvania',
'University of Pittsburgh, Bradford',
'University of Pittsburgh, Greensburg',
'University of Pittsburgh, Johnstown',
'University of Scranton',
'University of the Arts',
'University of the Sciences in Philadelphia',
'Ursinus College',
'Valley Forge Christian College',
'Villanova University',
'Washington and Jefferson College',
'Waynesburg College',
'West Chester University of Pennsylvania',
'Westminster College',
'Westminster Theological Seminary',
'Widener University',
'Wilkes University',
'Wilson College',
'York College of Pennsylvania',

//Rhode Island
'Brown University',
'Bryant College',
'Johnson & Wales University',
'Naval War College',
'New England Institute of Technology',
'Providence College',
'Rhode Island College',
'Rhode Island School of Design',
'Roger Williams University',
'Salve Regina University',
'University of Rhode Island',

//South Carolina
'Allen University',
'Anderson College',
'Benedict College',
'Bob Jones University',
'Charleston Southern University',
'The Citadel',
'Claflin University',
'Clemson University',
'Coastal Carolina University',
'Coker College',
'College of Charleston',
'Columbia College',
'Columbia International University',
'Converse College',
'Erskine College',
'Francis Marion University',
'Furman University',
'Johnson & Wales University-Charleston',
'Lander University',
'Limestone College',
'Medical University of South Carolina',
'Morris College',
'Newberry College',
'North Greenville College',
'Presbyterian College',
'Sherman College of Straight Chiropractic',
'South Carolina State University',
'Southern Wesleyan University',
'University of South Carolina, Aiken',
'University of South Carolina, Beaufort',
'University of South Carolina, Columbia',
'University of South Carolina, Lancaster',
'University of South Carolina, Spartanburg',
'University of South Carolina, Sumter',
'University of South Carolina, Union',
'Voorhees College',
'Winthrop University',
'Wofford College',

//South Dakota
'Augustana College',
'Black Hills State University',
'Dakota State University',
'Dakota Wesleyan University',
'Mount Marty College',
'National American University',
'Northern State University',
'Oglala Lakota College',
'Presentation College',
'Sinte Gleska University',
'South Dakota School of Mines & Technology',
'South Dakota State University',
'University of Sioux Falls',
'University of South Dakota',

//Tennessee
'Aquinas College',
'Austin Peay State University',
'Baptist Memorial College of Health Sciences',
'Belmont University',
'Bethel College',
'Bryan College',
'Carson-Newman College',
'Christian Brothers University',
'Church of God Theological Seminary',
'Crichton College',
'Cumberland University',
'East Tennessee State University',
'Fisk University',
'Freed-Hardeman University',
'Johnson Bible College',
'King College',
'Knoxville College',
'Lambuth University',
'Lane College',
'Lee University',
'LeMoyne-Owen College',
'Lincoln Memorial University',
'Lipscomb University',
'Martin Methodist College',
'Maryville College',
'Meharry Medical College',
'Memphis College of Art',
'Middle Tennessee State University',
'Milligan College',
'Rhodes College',
'Southern Adventist University',
'Southern College',
'Southern College of Optometry',
'Tennessee State University',
'Tennessee Technological University',
'Tennessee Temple University',
'Tennessee Wesleyan College',
'Trevecca Nazarene University',
'Tusculum College',
'Union University',
'University of Memphis',
'University of Tennessee, Chattanooga',
'University of Tennessee, Knoxville',
'University of Tennessee, Martin',
'University of Tennessee, Memphis',
'University of the South',
'Vanderbilt University',

//Texas
'Abilene Christian University',
'Ambassador University (closed spring 1997)',
'Amberton University',
'Angelo State University',
'Arlington Baptist College',
'Art Institute of Dallas',
'Austin College',
'Austin Presbyterian Theological Seminary',
'Baylor College of Medicine',
'Baylor University',
'College of Saint Thomas More',
'Concordia University-Austin',
'Criswell College',
'Dallas Baptist University',
'Dallas Christian College',
'Dallas Theological Seminary',
'DeVry University-Dallas',
'East Texas Baptist University',
'Episcopal Theological Seminary of the Southwest',
'Hardin-Simmons University',
'Houston Baptist University',
'Howard Payne University',
'Huston-Tillotson College',
'Institute for Christian Studies',
'ICI University',
'Jarvis Christian College',
'Lamar University',
'LeTourneau University',
'Lubbock Christian University',
'McMurry University',
'Midwestern State University',
'Northwood University',
'Our Lady of the Lake University',
'Parker College of Chiropractic',
'Paul Quinn College',
'Rice University',
'St. Edwards University',
'Saint Marys University of San Antonio',
'Sam Houston State University',
'Schreiner College',
'Southern Methodist University',
'South Texas College of Law',
'Southwest Texas State University',
'Southwestern Adventist University',
'Southwestern Assemblies of God University',
'Southwestern Baptist Theological Seminary',
'Southwestern Christian College',
'Southwestern University',
'Stephen F. Austin State University',
'Sul Ross State University',
'Texas A&M University , Baylor College of Dentistry',
'Texas A&M University , College Station',
'Texas A&M University , Commerce',
'Texas A&M University , Corpus Christi',
'Texas A&M University , Galveston',
'Texas A&M University , Health Science Center',
'Texas A&M University , Kingsville',
'Prairie View A&M University',
'Texas A&M University ,Tarleton State University',
'Texas A&M University , Texarkana',
'Texas A&M International University (Laredo)',
'West Texas A&M University',
'Texas Chiropractic College',
'Texas Christian University',
'Texas College',
'Texas Lutheran University',
'Texas Southern University',
'Texas Tech University',
'Texas Tech University-Health Sciences Center',
'Texas Wesleyan University',
'Texas Womans University',
'Trinity University',
'University of Dallas',
'University of Houston System',
'University of Houston System, Clear Lake',
'University of Houston System, Downtown',
'University of Houston System, Victoria',
'University of Mary Hardin-Baylor',
'University of North Texas',
'University of North Texas Health Science Center',
'University of Saint Thomas',
'University of Texas, Arlington',
'University of Texas, Austin',
'University of Texas, Brownsville',
'University of Texas, Dallas',
'University of Texas, El Paso',
'University of Texas, Pan American',
'University of Texas, Permian Basin',
'University of Texas, San Antonio',
'University of Texas, Tyler',
'University of Texas, Health Science Center-Houston',
'University of Texas, Health Science Center-San Antonio',
'University of Texas, Health Center-Tyler',
'University of Texas, M.D. Anderson Cancer Center',
'University of Texas, Medical Branch',
'University of Texas, Southwestern Medical Center at Dallas',
'University of the Incarnate Word',
'Wayland Baptist University',
'Wiley College',

//Utah
'Brigham Young University',
'College of Eastern Utah',
'Southern Utah University',
'University of Utah',
'Utah State University',
'Utah Valley State College',
'Weber State University',
'Westminster College',

//Vermont
'Bennington College',
'Burlington College',
'Castleton State University',
'Champlain College',
'College of St. Joseph',
'Goddard College',
'Green Mountain College',
'Johnson State College',
'Lyndon State College',
'Marlboro College',
'Middlebury College',
'Norwich University',
'Saint Michaels College',
'School for International Training',
'Southern Vermont College',
'Trinity College',
'University of Vermont',
'Vermont Law School',
'Vermont Technical College',

//Virginia
'Averett College',
'Bluefield College',
'Bridgewater College',
'Christendom College',
'Christopher Newport University',
'College of Health Sciences',
'College of William and Mary',
'Eastern Mennonite University',
'Eastern Virginia Medical School',
'Emory & Henry College',
'Ferrum College',
'George Mason University',
'George Washington University-Virginia Campus',
'Hampden-Sydney College',
'Hampton University',
'Hollins University',
'Institute of Textile Technology',
'James Madison University',
'Liberty University',
'Longwood University',
'Lynchburg College',
'Marine Corps University',
'Mary Baldwin College',
'Marymount University',
'Mary Washington College',
'Norfolk State University',
'Old Dominion University',
'Radford University',
'Randolph-Macon College',,
'Randolph-Macon Womans College',
'Regent University',
'Roanoke College',
'Saint Pauls College',
'Shenandoah University',
'Southern Virginia College',
'Sweet Briar College',
'University of Richmond',
'University of Virginia',
'University of Virginias College at Wise',
'Virginia Commonwealth University',
'Virginia Intermont College',
'Virginia Military Institute',
'Virginia Polytechnic Institute and State University',
'Virginia State University',
'Virginia Union University',
'Virginia Wesleyan College',
'Washington Bible College/Capital Bible Seminary',
'Washington & Lee University',

//Washington
'Antioch University-Seattle',
'Art Institute of Seattle',
'Bastyr University',
'Central Washington University',
'City University',
'Eastern Washington University',
'Evergreen State College',
'Gonzaga University',
'Henry Cogswell College',
'Heritage College',
'Northwest College of the Assemblies of God',
'Pacific Lutheran University',
'St. Martins College',
'Seattle Pacific University',
'Seattle University',
'Trinity Lutheran College',
'University of Puget Sound',
'University of Washington',
'University of Washington-Bothell',
'University of Washington-Tacoma',
'Walla Walla College',
'Washington State University at Pullman',
'Washington State University at Spokane',
'Washington State University at Tri-Cities',
'Washington State University at Vancouver',
'Western Washington University',
'Whitman College',
'Whitworth College',

//West Virginia
'Alderson-Broaddus College',
'Bethany College',
'Bluefield State College',
'Concord College',
'Davis & Elkins College',
'Fairmont State College',
'Glenville State College',
'Marshall University',
'Mountain State University',
'Ohio Valley College',
'Salem International University',
'Shepherd College',
'University of Charleston',
'West Liberty University',
'West Virginia State College',
'West Virginia University',
'West Virginia University Institute of Technology',
'West Virginia University at Parkersburg',
'West Virginia Wesleyan College',
'Wheeling Jesuit University',

//Wisconsin
'Alverno College',
'Beloit College',
'Cardinal Stritch College',
'Carroll College',
'Carthage College',
'Concordia University-Wisconsin',
'Edgewood College',
'Lakeland College',
'Lawrence University',
'Maranatha Baptist Bible College',
'Marian College of Fond du Lac',
'Marquette University',
'Medical College of Wisconsin',
'Milwaukee School of Engineering',
'Mount Mary College',
'Mount Senario College',
'Northland College',
'Ripon College',
'St. Norbert College',
'Silver Lake College',
'University of Wisconsin, Eau Claire',
'University of Wisconsin, Green Bay',
'University of Wisconsin, LaCrosse',
'University of Wisconsin, Madison',
'University of Wisconsin, Milwaukee',
'University of Wisconsin, Oshkosh',
'University of Wisconsin, Parkside',
'University of Wisconsin, Platteville',
'University of Wisconsin, River Falls',
'University of Wisconsin, Stevens Point',
'University of Wisconsin, Stout',
'University of Wisconsin, Superior',
'University of Wisconsin, Whitewater',
'Viterbo College',
'Wisconsin Lutheran College',
'Wisconsin School of Professional Psychology',

//Wyoming
'University of Wyoming',
]

function newQuote() {
  var randomNumber = Math.floor(Math.random() * (quotes.length));
  document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber].fontsize(7).fontcolor("#a34e9e");
}
